[package]
license.workspace = true
name = "game_sim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
game_shared = { path = "../game_shared" }
log.workspace = true
vleue_navigator = "0.16.0"

[features]
default = []
bevy = ["dep:bevy"]

[dependencies.bevy]
workspace = true
features = ["std"]
optional = true
