use super::*;
use crate::codec::{self, BoundedVec, Validate};
use serde::{Deserialize, Serialize, de::DeserializeOwned};

/// Trusted bounded value-codec contract. Implementations generated by `schema!`
/// and supplied below enforce the work/size budgets. Arbitrary serde types do
/// not gain this trait: unbounded Vec/String are deliberately unsupported.
pub trait FieldValue: Clone + PartialEq + Sized + 'static {
    fn inspect(
        spec: &FieldSpec,
        inspection: &mut Inspection,
        depth: usize,
    ) -> Result<(), SchemaError>;
    fn maximum_size(work: &mut Work, depth: usize) -> Result<usize, SchemaError>;
    fn value_size(
        &self,
        spec: &FieldSpec,
        work: &mut Work,
        depth: usize,
    ) -> Result<usize, SchemaError>;
    fn write(&self, out: &mut Vec<u8>, work: &mut Work, depth: usize) -> Result<(), SchemaError>;
    fn read(bytes: &[u8], work: &mut Work, depth: usize) -> Result<Self, SchemaError>;
}
trait Scalar: Clone + PartialEq + Serialize + DeserializeOwned + Copy {
    fn valid(self) -> bool {
        true
    }
    fn canonical(self) -> Self {
        self
    }
}
#[derive(Serialize, Deserialize)]
#[serde(transparent)]
struct ScalarWire<T>(T);
impl<T: Scalar> Validate for ScalarWire<T> {
    fn validate(&self) -> Result<(), codec::CodecError> {
        if self.0.valid() {
            Ok(())
        } else {
            Err(codec::CodecError::InvalidPayload("nonfinite scalar".into()))
        }
    }
}
fn write_scalar<T: Scalar>(
    value: T,
    out: &mut Vec<u8>,
    work: &mut Work,
) -> Result<(), SchemaError> {
    let bytes = codec::encode_payload(&ScalarWire(value.canonical()), 16)
        .map_err(|_| SchemaError::InvalidEncoding)?;
    work.append(out, &bytes)
}
fn read_scalar<T: Scalar>(bytes: &[u8]) -> Result<T, SchemaError> {
    codec::decode_payload::<ScalarWire<T>>(bytes, 16)
        .map(|v| v.0.canonical())
        .map_err(|_| SchemaError::InvalidEncoding)
}
fn discrete(spec: &FieldSpec) -> Result<(), SchemaError> {
    if matches!(
        spec.interpolation,
        Interpolation::None | Interpolation::Step
    ) {
        Ok(())
    } else {
        Err(SchemaError::InvalidInterpolation)
    }
}
macro_rules! integer {
    ($ty:ty,$tag:expr,$range:ident,$bound:ty) => {
        impl Scalar for $ty {}
        impl FieldValue for $ty {
            fn inspect(spec: &FieldSpec, i: &mut Inspection, _: usize) -> Result<(), SchemaError> {
                discrete(spec)?;
                let Range::$range { minimum, maximum } = spec.range else {
                    return Err(SchemaError::InvalidRange);
                };
                if minimum > maximum
                    || minimum < (<$ty>::MIN as $bound)
                    || maximum > (<$ty>::MAX as $bound)
                {
                    return Err(SchemaError::InvalidRange);
                }
                i.tag($tag);
                Ok(())
            }
            fn maximum_size(w: &mut Work, d: usize) -> Result<usize, SchemaError> {
                w.node(d)?;
                Ok(std::mem::size_of::<Self>())
            }
            fn value_size(
                &self,
                spec: &FieldSpec,
                w: &mut Work,
                d: usize,
            ) -> Result<usize, SchemaError> {
                w.node(d)?;
                let Range::$range { minimum, maximum } = spec.range else {
                    return Err(SchemaError::InvalidRange);
                };
                if (*self as $bound) < minimum || (*self as $bound) > maximum {
                    return Err(SchemaError::OutOfRange);
                }
                Ok(std::mem::size_of::<Self>())
            }
            fn write(&self, out: &mut Vec<u8>, w: &mut Work, d: usize) -> Result<(), SchemaError> {
                w.node(d)?;
                write_scalar(*self, out, w)
            }
            fn read(bytes: &[u8], w: &mut Work, d: usize) -> Result<Self, SchemaError> {
                w.node(d)?;
                read_scalar(bytes)
            }
        }
    };
}
integer!(u8, 1, Unsigned, u64);
integer!(u16, 2, Unsigned, u64);
integer!(u32, 3, Unsigned, u64);
integer!(u64, 4, Unsigned, u64);
integer!(i8, 5, Signed, i64);
integer!(i16, 6, Signed, i64);
integer!(i32, 7, Signed, i64);
integer!(i64, 8, Signed, i64);
impl Scalar for bool {}
impl FieldValue for bool {
    fn inspect(s: &FieldSpec, i: &mut Inspection, _: usize) -> Result<(), SchemaError> {
        discrete(s)?;
        if s.range != Range::None {
            return Err(SchemaError::InvalidRange);
        }
        i.tag(9);
        Ok(())
    }
    fn maximum_size(w: &mut Work, d: usize) -> Result<usize, SchemaError> {
        w.node(d)?;
        Ok(1)
    }
    fn value_size(&self, s: &FieldSpec, w: &mut Work, d: usize) -> Result<usize, SchemaError> {
        w.node(d)?;
        if s.range != Range::None {
            return Err(SchemaError::InvalidRange);
        }
        Ok(1)
    }
    fn write(&self, out: &mut Vec<u8>, w: &mut Work, d: usize) -> Result<(), SchemaError> {
        w.node(d)?;
        write_scalar(*self, out, w)
    }
    fn read(bytes: &[u8], w: &mut Work, d: usize) -> Result<Self, SchemaError> {
        w.node(d)?;
        read_scalar(bytes)
    }
}
macro_rules! float {
    ($ty:ty,$range:ident,$tag:expr) => {
        impl Scalar for $ty {
            fn valid(self) -> bool {
                self.is_finite()
            }
            fn canonical(self) -> Self {
                if self == 0.0 { 0.0 } else { self }
            }
        }
        impl FieldValue for $ty {
            fn inspect(s: &FieldSpec, i: &mut Inspection, _: usize) -> Result<(), SchemaError> {
                let Range::$range { minimum, maximum } = s.range else {
                    return Err(SchemaError::InvalidRange);
                };
                if !minimum.is_finite() || !maximum.is_finite() || minimum > maximum {
                    return Err(SchemaError::InvalidRange);
                }
                if s.interpolation == Interpolation::AngleRadians && s.units != Units::Radians {
                    return Err(SchemaError::InvalidInterpolation);
                }
                i.tag($tag);
                Ok(())
            }
            fn maximum_size(w: &mut Work, d: usize) -> Result<usize, SchemaError> {
                w.node(d)?;
                Ok(std::mem::size_of::<Self>())
            }
            fn value_size(
                &self,
                s: &FieldSpec,
                w: &mut Work,
                d: usize,
            ) -> Result<usize, SchemaError> {
                w.node(d)?;
                if !self.is_finite() {
                    return Err(SchemaError::NonFinite);
                }
                let Range::$range { minimum, maximum } = s.range else {
                    return Err(SchemaError::InvalidRange);
                };
                if *self < minimum || *self > maximum {
                    return Err(SchemaError::OutOfRange);
                }
                Ok(std::mem::size_of::<Self>())
            }
            fn write(&self, out: &mut Vec<u8>, w: &mut Work, d: usize) -> Result<(), SchemaError> {
                w.node(d)?;
                write_scalar(*self, out, w)
            }
            fn read(bytes: &[u8], w: &mut Work, d: usize) -> Result<Self, SchemaError> {
                w.node(d)?;
                read_scalar(bytes)
            }
        }
    };
}
float!(f32, Float32, 10);
float!(f64, Float64, 11);
fn sequence_max<T: FieldValue, const N: usize>(
    w: &mut Work,
    d: usize,
) -> Result<usize, SchemaError> {
    w.node(d)?;
    w.count(N)?;
    w.reserve::<T>(N)?;
    let before = w.checkpoint();
    let element = T::maximum_size(w, d + 1)?;
    w.repeat_since(before, N.saturating_sub(1))?;
    w.size(
        4usize
            .checked_add(
                N.checked_mul(4usize.checked_add(element).ok_or(SchemaError::WireBudget)?)
                    .ok_or(SchemaError::WireBudget)?,
            )
            .ok_or(SchemaError::WireBudget)?,
    )
}
fn sequence_size<T: FieldValue>(
    values: &[T],
    spec: &FieldSpec,
    w: &mut Work,
    d: usize,
) -> Result<usize, SchemaError> {
    w.node(d)?;
    w.count(values.len())?;
    let mut bytes = 4;
    for value in values {
        let value_bytes = value.value_size(spec, w, d + 1)?;
        bytes = w.size(bytes + 4 + value_bytes)?;
    }
    Ok(bytes)
}
fn sequence_write<T: FieldValue>(
    values: &[T],
    out: &mut Vec<u8>,
    w: &mut Work,
    d: usize,
) -> Result<(), SchemaError> {
    w.node(d)?;
    w.count(values.len())?;
    w.append(out, &(values.len() as u32).to_le_bytes())?;
    for value in values {
        let start = out.len();
        w.append(out, &[0; 4])?;
        value.write(out, w, d + 1)?;
        let size = u32::try_from(out.len() - start - 4).map_err(|_| SchemaError::WireBudget)?;
        out[start..start + 4].copy_from_slice(&size.to_le_bytes());
    }
    Ok(())
}
fn sequence_read<T: FieldValue, const N: usize>(
    bytes: &[u8],
    fixed: bool,
    w: &mut Work,
    d: usize,
) -> Result<Vec<T>, SchemaError> {
    w.node(d)?;
    let mut reader = Reader::new(bytes);
    let count = reader.u32()? as usize;
    w.count(count)?;
    if count > N || (fixed && count != N) {
        return Err(SchemaError::CountBudget);
    }
    // At least one length per element must exist before reserving typed storage.
    if count.checked_mul(4).is_none_or(|n| n > reader.remaining()) {
        return Err(SchemaError::Truncated);
    }
    w.reserve::<T>(count)?;
    let mut values = Vec::with_capacity(count);
    for _ in 0..count {
        let size = reader.u32()? as usize;
        let body = reader.take(size)?;
        values.push(T::read(body, w, d + 1)?);
    }
    reader.finish()?;
    Ok(values)
}
impl<T: FieldValue, const N: usize> FieldValue for [T; N] {
    fn inspect(s: &FieldSpec, i: &mut Inspection, d: usize) -> Result<(), SchemaError> {
        i.count(N)?;
        i.tag(12);
        i.number(N as u64);
        T::inspect(s, i, d + 1)
    }
    fn maximum_size(w: &mut Work, d: usize) -> Result<usize, SchemaError> {
        sequence_max::<T, N>(w, d)
    }
    fn value_size(&self, s: &FieldSpec, w: &mut Work, d: usize) -> Result<usize, SchemaError> {
        sequence_size(self, s, w, d)
    }
    fn write(&self, out: &mut Vec<u8>, w: &mut Work, d: usize) -> Result<(), SchemaError> {
        sequence_write(self, out, w, d)
    }
    fn read(bytes: &[u8], w: &mut Work, d: usize) -> Result<Self, SchemaError> {
        sequence_read::<T, N>(bytes, true, w, d)?
            .try_into()
            .map_err(|_| SchemaError::CountBudget)
    }
}
impl<T: FieldValue, const N: usize> FieldValue for BoundedVec<T, N> {
    fn inspect(s: &FieldSpec, i: &mut Inspection, d: usize) -> Result<(), SchemaError> {
        i.count(N)?;
        i.tag(13);
        i.number(N as u64);
        T::inspect(s, i, d + 1)
    }
    fn maximum_size(w: &mut Work, d: usize) -> Result<usize, SchemaError> {
        sequence_max::<T, N>(w, d)
    }
    fn value_size(&self, s: &FieldSpec, w: &mut Work, d: usize) -> Result<usize, SchemaError> {
        sequence_size(self.as_slice(), s, w, d)
    }
    fn write(&self, out: &mut Vec<u8>, w: &mut Work, d: usize) -> Result<(), SchemaError> {
        sequence_write(self.as_slice(), out, w, d)
    }
    fn read(bytes: &[u8], w: &mut Work, d: usize) -> Result<Self, SchemaError> {
        BoundedVec::new(sequence_read::<T, N>(bytes, false, w, d)?)
            .map_err(|_| SchemaError::CountBudget)
    }
}
