[package]
license.workspace = true
name = "game_server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum = "0.8.8"
bytes = "1"
axum-server = { version = "0.7.2", features = ["tls-rustls"] }
bevy = { workspace = true, features = ["std", "multi_threaded"] }
clap.workspace = true
env_logger.workspace = true
game_shared = { path = "../shared/protocol" }
game_sim = { path = "../shared/simulation", features = ["bevy"] }
log.workspace = true
renet.workspace = true
rtrb.workspace = true
renet-cross = { workspace = true, features = ["axum"] }
serde.workspace = true
serde_json.workspace = true
time = { version = "0.3.36", features = ["formatting", "macros"] }
tokio.workspace = true
tower-http = { version = "0.6.6", features = ["cors"] }

[features]
default = []
ui = ["bevy/default", "bevy/bevy_dev_tools"]
