[package]
license.workspace = true
name = "game_sim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
game_shared = { path = "../protocol" }
log.workspace = true
game_replication = { path = "../replication" }
vleue_navigator = "0.16.0"

[features]
default = []
bevy = []

[dependencies.bevy]
workspace = true
features = ["std"]


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy = { workspace = true, features = ["std", "multi_threaded"] }
