[package]
name="dreamwake_server"
version.workspace=true
edition.workspace=true
rust-version.workspace=true
license.workspace=true
[[bin]]
name="game_server"
path="src/main.rs"
[dependencies]
serde.workspace = true
bevy={workspace=true,features=["std"]}
engine_server={path="../../../engine/server"}
engine_net={path="../../../engine/net"}
dreamwake_protocol={path="../protocol"}
dreamwake_sim={path="../simulation"}
clap.workspace=true
env_logger.workspace=true
log.workspace=true
serde_json.workspace=true
renet.workspace=true
renet-cross.workspace=true

blake3.workspace=true

[dev-dependencies]
engine_core={path="../../../engine/core"}
